#!/usr/bin/env bash

# Função para verificar se o usuário é root ou está usando sudo
check_root() {
    if [ "$EUID" -ne 0 ]; then
        echo "Erro: Este script precisa ser executado como root ou com sudo." >&2
        exit 1
    fi
}

update=("$@")
export update

# shellcheck source=/dev/null
export_mod() {
source "modulos/ambiente"
source "modulos/diretorio"
source "modulos/lib"
source "modulos/ctsat"
source "modulos/modphp"
source "modulos/codfon"
source "modulos/jpdvgui6"
}

# Função de ajuda
function exibir_ajuda {
    echo "Uso: $0 [opção]"
    echo "Opções disponíveis:"
    echo "  --lib|-l       : Atualiza as bibliotecas do PDV"
    echo "  --ctsat|-c     : Atualiza o ctsat do PDV"
    echo "  --modulo|-m    : Atualiza o moduloPHPPDV do PDV"
    echo "  --zman|-z      : Atualiza o CODFON do PDV"
    echo "  --jpdvgui6|-j  : Atualiza o Java do PDV"
    echo "  --pdv|-p       : Atualiza todos os módulos {-l,-c,-m,-z,-j}"
    echo "  --help|p       : Exibe esta ajuda e sai"
    exit 0
}

# Chamando a função para verificar se é root
check_root

# Exporta os módulos
export_mod

# Chama as funções para PDV
case $update in
    --lib|-l)
        # Atualiza as bibliotecas do PDV
        lib_check
        ;;
    --ctsat|-c)
        # Atualiza o ctsat do PDV
        ctsat_check
        ;;
    --modulo|-m)
        # Atualiza o moduloPHPPDV do PDV
        modulo_check
        ;;
    --zman|-z)
        # Atualiza o CODFON do PDV
        zman_check
        ;;
    --jpdvgui6|-j)
        # Atualiza o Java do PDV
        jpdvgui6_check
        ;;
    --pdv|-p)
        # Atualiza todos os módulos {-l,-c,-m,-z,-j}
        lib_check
        modulo_check
        zman_check
        jpdvgui6_check
        ;;
    --help|-h)
        # Exibe esta ajuda e sai
        exibir_ajuda
        ;;
    *)
        # Caso vazio, exibe erro e sai
        echo "Função desconhecida, digite {--help ou -h}."
        exit 1
        ;;
esac
