#!/bin/env bash

update=("$@")
export update

# shellcheck source=/dev/null
export_mod() {
source "modulos/ambiente"
source "modulos/diretorio"
source "modulos/lib"
source "modulos/ctsat"
source "modulos/modphp"
source "modulos/codfon"
source "modulos/jpdvgui6"
}
export_mod

# Chama as funções para PDV
lib_check
ctsat_check
modulo_check
zman_check
jpdvgui6_check
